import { useEffect, useState } from "react";
import { BookOpen, Plus, RefreshCw, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const API_TOKEN=import.meta.env.VITE_API_ACCESS_TOKEN?.trim()??"";
const h=(extra?:HeadersInit):HeadersInit=>API_TOKEN?{...(extra||{}),"X-API-Key":API_TOKEN}:(extra||{});
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:h(init?.headers)});if(!r.ok)throw new Error(await r.text());return r.json();}

type Item={id:string;title:string;category:string;content:string;tags:string;active:number};
const empty={title:"",category:"product",content:"",tags:"",active:true};
export function KnowledgePage(){
  const [items,setItems]=useState<Item[]>([]);const [selected,setSelected]=useState<Set<string>>(new Set());const [search,setSearch]=useState("");const [draft,setDraft]=useState<any>(empty);const [show,setShow]=useState(false);const [message,setMessage]=useState("");
  const load=async()=>{try{const d=await api(`/api/v1/knowledge?search=${encodeURIComponent(search)}`);setItems(d.items||[]);setSelected(new Set());}catch(e){setMessage(`加载失败：${e}`);}};useEffect(()=>{void load();},[]);
  const save=async()=>{try{await api("/api/v1/knowledge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});setDraft(empty);setShow(false);setMessage("知识已保存");await load();}catch(e){setMessage(`保存失败：${e}`);}};
  const del=async()=>{if(!selected.size||!confirm(`删除 ${selected.size} 条知识？`))return;try{const d=await api("/api/v1/knowledge/delete-many",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:Array.from(selected)})});setMessage(`已删除 ${d.deleted||0} 条`);await load();}catch(e){setMessage(`删除失败：${e}`);}};
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><BookOpen className="h-6 w-6"/>企业知识库</h1><p className="mt-1 text-sm text-muted-foreground">保存产品、MOQ、认证、交期、包装、公司能力、案例和常见异议；AI 销售计划会优先引用这些事实。</p></div><Button onClick={()=>setShow(!show)}><Plus className="mr-2 h-4 w-4"/>新增知识</Button></div>{message&&<div className="rounded-md border bg-muted/40 px-3 py-2 text-sm">{message}</div>}
  {show&&<Card><CardHeader><CardTitle className="text-base">新增知识</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 md:grid-cols-3"><Input placeholder="标题，例如：Smart Ring MOQ" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><select className="h-10 rounded-md border bg-background px-3" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}><option value="product">产品</option><option value="pricing">价格/MOQ</option><option value="certification">认证</option><option value="delivery">交期</option><option value="packaging">包装</option><option value="company">公司能力</option><option value="case">案例</option><option value="objection">常见异议</option><option value="general">其他</option></select><Input placeholder="标签，逗号分隔" value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})}/></div><textarea className="min-h-40 w-full rounded-md border bg-background p-3 text-sm" placeholder="写入准确、可对外使用的事实。AI 不会把知识库以外的参数自动当成事实。" value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})}/><div className="flex gap-2"><Button onClick={()=>void save()}>保存</Button><Button variant="outline" onClick={()=>setShow(false)}>取消</Button></div></CardContent></Card>}
  <Card><CardContent className="pt-6"><div className="mb-4 flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="搜索知识库" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void load()}/></div><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>刷新</Button><Button variant="destructive" disabled={!selected.size} onClick={()=>void del()}><Trash2 className="mr-2 h-4 w-4"/>删除 ({selected.size})</Button></div><div className="space-y-3">{items.map(x=><div key={x.id} className="rounded-md border p-4"><div className="flex gap-3"><input type="checkbox" checked={selected.has(x.id)} onChange={()=>{const n=new Set(selected);n.has(x.id)?n.delete(x.id):n.add(x.id);setSelected(n);}}/><div className="flex-1"><div className="flex items-center gap-2"><span className="font-semibold">{x.title}</span><span className="rounded bg-muted px-2 py-0.5 text-xs">{x.category}</span></div><div className="mt-2 whitespace-pre-wrap text-sm">{x.content}</div>{x.tags&&<div className="mt-2 text-xs text-muted-foreground">标签：{x.tags}</div>}</div></div></div>)}{!items.length&&<div className="p-8 text-center text-muted-foreground">知识库为空。建议先录入产品、MOQ、认证、交期和公司能力。</div>}</div></CardContent></Card></div>;
}
